import React from 'react';
import { DashboardWidgetMeta } from '../../types';

export const DASHBOARD_AVAILABLE_WIDGETS: DashboardWidgetMeta[] = [
  {
    id: 'kpis-primary',
    title: 'Tarjetas de Indicadores Clave (KPIs)',
    category: 'kpi',
    description: 'Resumen global de radicaciones, resueltos, casos en progreso, abiertos y cumplimiento SLA.',
    iconName: 'Sparkles',
    defaultColSpan: 3,
  },
  {
    id: 'chart-status-donut',
    title: 'Distribución por Estado de Gestión',
    category: 'operativo',
    description: 'Gráfico circular del ciclo de vida de los reportes (Abiertos, En Progreso, Resueltos).',
    iconName: 'PieChart',
    defaultColSpan: 1,
  },
  {
    id: 'chart-category-volume',
    title: 'Volumen por Categoría de Incidencia',
    category: 'distribucion',
    description: 'Ranking de solicitudes por tipo de servicio comunal (Alumbrado, Vialidad, Agua, etc.).',
    iconName: 'BarChart3',
    defaultColSpan: 2,
  },
  {
    id: 'chart-sector-distribution',
    title: 'Mapa de Incidencia por Sector Comunal',
    category: 'distribucion',
    description: 'Distribución territorial y carga de trabajo en cada comunidad de la Junta Comunal.',
    iconName: 'MapPin',
    defaultColSpan: 2,
  },
  {
    id: 'chart-time-trend',
    title: 'Tendencia Cronológica de Radicación',
    category: 'tendencia',
    description: 'Curva temporal de nuevos reportes generados a lo largo de los días y semanas.',
    iconName: 'TrendingUp',
    defaultColSpan: 1,
  },
  {
    id: 'chart-priority-matrix',
    title: 'Matriz de Severidad & Prioridad',
    category: 'operativo',
    description: 'Segmentación de casos entre Urgentes, Altos, Medios y Bajos con tiempo de atención.',
    iconName: 'AlertTriangle',
    defaultColSpan: 1,
  },
  {
    id: 'chart-sla-performance',
    title: 'Índice de Cumplimiento de SLA por Categoría',
    category: 'operativo',
    description: 'Porcentaje de resolución dentro del plazo establecido para cada tipología.',
    iconName: 'Clock',
    defaultColSpan: 2,
  },
  {
    id: 'chart-demographics-gender',
    title: 'Perfil Demográfico: Género de Solicitantes',
    category: 'demografia',
    description: 'Proporción de vecinos y vecinas que radican solicitudes en la comunidad.',
    iconName: 'Users',
    defaultColSpan: 1,
  },
  {
    id: 'chart-demographics-age',
    title: 'Distribución por Grupos Etarios',
    category: 'demografia',
    description: 'Participación ciudadana dividida por rangos de edad (Jóvenes, Adultos, Adultos Mayores).',
    iconName: 'Users',
    defaultColSpan: 1,
  },
  {
    id: 'chart-channels-intake',
    title: 'Canales y Sedes de Radicación',
    category: 'distribucion',
    description: 'Origen de las solicitudes: Portal Web, Ventanilla Presencial, Cuadrilla en Campo, etc.',
    iconName: 'Building',
    defaultColSpan: 1,
  },
  {
    id: 'table-active-incidents',
    title: 'Cuadro Dinámico de Incidencias Críticas Activas',
    category: 'operativo',
    description: 'Lista detallada de casos pendientes con conteo regresivo de SLA y asignación.',
    iconName: 'Layers',
    defaultColSpan: 3,
  },
];
